MANAGER_EXPENSE_CATEGORIES = [
    "Vehicle servicing",
    "Transportation",
    "Carriage Inwards",
    "Creditors",
    "Eggs",
    "Delivery",
    "Delievery",
    "Fuel",
    "SUSU Withdrawal",
    "Marketing (Activations)",
    "Stock (mini)",
    "Airtime",
    "Pre Paid light",
    "Serving",
    "Utilities",
    "Miscellaneous",
    "Salary (Monthly)",
    "Salaries",
    "Police Arrest",
    "AMA",
    "Rewards (commissions)",
    "Rewards (commisions)",
]
