import { useCallback, useEffect, useState } from "react";
import { Archive, ArchiveRestore, Search, Users, AlertTriangle, ChevronLeft, ChevronRight } from "lucide-react";
import { useTheme } from "./ThemeContext";

type Customer = { id:string; name:string; phone:string; branch:string; code:string; status:string; archivedAt:string; archivedReason:string };
type Tab = "archive" | "archived";

export function ArchivedCustomersPage() {
  const { t } = useTheme();
  const [tab,setTab] = useState<Tab>("archive");
  const [query,setQuery] = useState(""); const [submitted,setSubmitted] = useState("");
  const [rows,setRows] = useState<Customer[]>([]); const [selected,setSelected] = useState<string[]>([]);
  const [reason,setReason] = useState(""); const [loading,setLoading] = useState(false); const [saving,setSaving] = useState(false);
  const [error,setError] = useState(""); const [notice,setNotice] = useState("");
  const [page,setPage] = useState(1); const [total,setTotal] = useState(0); const [totalPages,setTotalPages] = useState(1);

  const load = useCallback(async (activeTab=tab, search=submitted, targetPage=page) => {
    if(activeTab==="archive" && search.trim().length<2){setRows([]);setTotal(0);return;}
    setLoading(true);setError("");
    try { const path=activeTab==="archive"?`/api/customer-support/customers/archive/active?q=${encodeURIComponent(search)}`:`/api/customer-support/customers/archive/archived?q=${encodeURIComponent(search)}&page=${targetPage}`; const response=await fetch(path,{credentials:"same-origin"}); const data=await response.json(); if(!response.ok||!data.ok)throw new Error(data.message||"Unable to load customers."); setRows(data.customers||[]);setTotal(data.total??data.customers?.length??0);setTotalPages(data.totalPages||1);setSelected([]); }
    catch(e){setError(e instanceof Error?e.message:"Unable to load customers.");} finally{setLoading(false);}
  },[page,submitted,tab]);
  useEffect(()=>{if(tab==="archived")void load("archived",submitted,page);},[tab,page]);
  const switchTab=(next:Tab)=>{setTab(next);setQuery("");setSubmitted("");setRows([]);setSelected([]);setNotice("");setError("");setPage(1);};
  const search=()=>{const value=query.trim();setSubmitted(value);setPage(1);void load(tab,value,1);};
  const toggle=(id:string)=>setSelected(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);
  const toggleAll=()=>setSelected(selected.length===rows.length?[]:rows.map(row=>row.id));
  const act=async()=>{if(!selected.length){setError("Select at least one customer.");return;} const verb=tab==="archive"?"archive":"restore"; if(!window.confirm(`Are you sure you want to ${verb} ${selected.length} customer${selected.length===1?"":"s"}?`))return; setSaving(true);setError("");setNotice(""); try { const endpoint=tab==="archive"?"/api/customer-support/customers/archive":"/api/customer-support/customers/archive/unarchive"; const response=await fetch(endpoint,{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({customer_ids:selected,reason:reason.trim()})}); const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.message||`Unable to ${verb} customers.`);const count=tab==="archive"?data.counts?.archived:data.counts?.unarchived;setNotice(`${count||0} customer${count===1?"":"s"} ${tab==="archive"?"archived":"restored"} successfully.`);setReason("");await load(tab,submitted,page);window.dispatchEvent(new Event("customer-support-customers-changed")); }catch(e){setError(e instanceof Error?e.message:`Unable to ${verb} customers.`);}finally{setSaving(false);}};
  const card={background:t.cardBg,border:`1px solid ${t.cardBorder}`,borderRadius:t.cardRadius,boxShadow:t.cardShadow};

  return <div style={{padding:"32px",maxWidth:1500,margin:"0 auto",color:t.textPrimary}}>
    <div className="mb-7"><h1 style={{fontSize:"1.6rem",fontWeight:700,letterSpacing:"-.04em"}}>Archived Customers</h1><p style={{color:t.textTertiary,marginTop:6}}>Archive inactive customer records or restore previously archived customers.</p></div>
    <div className="flex gap-2 mb-5" style={{...card,padding:6,width:"fit-content"}}>{([{key:"archive",label:"Archive Customers",icon:Archive},{key:"archived",label:"Archived Customers",icon:ArchiveRestore}] as const).map(item=><button key={item.key} onClick={()=>switchTab(item.key)} className="flex items-center gap-2 rounded-xl px-4 py-2.5" style={{background:tab===item.key?t.accent:"transparent",color:tab===item.key?"white":t.textSecondary,fontWeight:600}}><item.icon size={16}/>{item.label}</button>)}</div>
    {(error||notice)&&<div className="flex items-center gap-2 mb-5 rounded-xl p-4" style={{background:error?"#FEE2E2":"#DCFCE7",color:error?"#B91C1C":"#166534"}}>{error&&<AlertTriangle size={16}/>} {error||notice}</div>}
    <div style={{...card,padding:24}}>
      <div className="flex flex-wrap items-end gap-3 mb-5"><div className="flex-1 min-w-64"><label className="block text-xs font-semibold uppercase mb-2" style={{color:t.textMuted}}>Search {tab==="archive"?"active":"archived"} customers</label><div className="relative"><Search size={16} className="absolute left-3 top-3" color={t.textMuted}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")search();}} placeholder="Name, phone number, customer code or ID" className="w-full rounded-xl py-2.5 pl-10 pr-3 outline-none" style={{background:t.surface,border:`1px solid ${t.border}`,color:t.textPrimary}}/></div></div><button onClick={search} disabled={loading} className="rounded-xl px-5 py-2.5 text-white font-semibold" style={{background:t.accent}}>{loading?"Searching…":"Search"}</button></div>
      <div className="flex flex-wrap items-end gap-3 mb-5"><div className="flex-1 min-w-64"><label className="block text-xs font-semibold uppercase mb-2" style={{color:t.textMuted}}>{tab==="archive"?"Archive":"Restore"} reason</label><input value={reason} onChange={e=>setReason(e.target.value)} placeholder={tab==="archive"?"Why is this customer being archived?":"Why is this customer being restored?"} className="w-full rounded-xl px-3 py-2.5 outline-none" style={{background:t.surface,border:`1px solid ${t.border}`,color:t.textPrimary}}/></div><button onClick={act} disabled={saving||!selected.length} className="flex items-center gap-2 rounded-xl px-5 py-2.5 text-white font-semibold disabled:opacity-50" style={{background:tab==="archive"?"#DC2626":"#16A34A"}}>{tab==="archive"?<Archive size={16}/>:<ArchiveRestore size={16}/>} {saving?"Working…":tab==="archive"?`Archive Selected (${selected.length})`:`Restore Selected (${selected.length})`}</button></div>
      <div className="overflow-x-auto rounded-xl" style={{border:`1px solid ${t.tableDivider}`}}><table className="w-full"><thead><tr style={{background:t.tableHeaderBg}}><th className="p-4 text-left"><input type="checkbox" checked={!!rows.length&&selected.length===rows.length} onChange={toggleAll}/></th>{["Customer","Phone","Customer Code","Branch",tab==="archive"?"Status":"Archived","Reason"].map(h=><th key={h} className="p-4 text-left text-xs uppercase" style={{color:t.textMuted}}>{h}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={row.id} style={{borderTop:index?`1px solid ${t.tableDivider}`:"none"}}><td className="p-4"><input type="checkbox" checked={selected.includes(row.id)} onChange={()=>toggle(row.id)}/></td><td className="p-4"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full font-bold" style={{background:t.accentSubtle,color:t.accent}}>{row.name.split(" ").map(v=>v[0]).slice(0,2).join("")}</div><span className="font-semibold">{row.name}</span></div></td><td className="p-4" style={{color:t.textSecondary}}>{row.phone}</td><td className="p-4 font-mono text-sm" style={{color:t.textSecondary}}>{row.code||"—"}</td><td className="p-4" style={{color:t.textSecondary}}>{row.branch||"—"}</td><td className="p-4" style={{color:t.textSecondary}}>{tab==="archive"?(row.status||"Active"):(row.archivedAt||"—")}</td><td className="p-4" style={{color:t.textSecondary}}>{row.archivedReason||"—"}</td></tr>)}</tbody></table>{!loading&&!rows.length&&<div className="flex flex-col items-center py-14" style={{color:t.textMuted}}><Users size={30}/><p className="mt-3">{tab==="archive"&&!submitted?"Search for a customer to archive.":"No customers found."}</p></div>}</div>
      {tab==="archived"&&total>0&&<div className="flex items-center justify-between mt-5"><span className="text-sm" style={{color:t.textMuted}}>{total} archived customer{total===1?"":"s"}</span><div className="flex items-center gap-2"><button disabled={page<=1} onClick={()=>setPage(value=>value-1)} className="rounded-lg p-2 disabled:opacity-40" style={{border:`1px solid ${t.border}`}}><ChevronLeft size={16}/></button><span className="text-sm">Page {page} of {totalPages}</span><button disabled={page>=totalPages} onClick={()=>setPage(value=>value+1)} className="rounded-lg p-2 disabled:opacity-40" style={{border:`1px solid ${t.border}`}}><ChevronRight size={16}/></button></div></div>}
    </div>
  </div>;
}
