import { useEffect, useState, type ReactNode } from "react";
import { CheckCircle2, ChevronLeft, ChevronRight, Clock3, Download, Eye, Package, RefreshCw, Search, Truck, X } from "lucide-react";
import { useTheme } from "./ThemeContext";

type History = { status: string; label: string; actorName: string; actorRole: string; timestamp: string; notes: string };
type Delivery = { id: string; customerId: string; customerName: string; customerPhone: string; productName: string; productImage: string; purchaseType: string; quantity: number; productTotal: number; amountPaid: number; amountLeft: number; branch: string; agentName: string; status: string; statusLabel: string; submittedAt: string; updatedAt: string; daysWaiting: number; source: string; history: History[] };
type Counts = { total: number; open: number; pending: number; packaging: number; delivering: number; delivered: number };
const EMPTY_COUNTS: Counts = { total: 0, open: 0, pending: 0, packaging: 0, delivering: 0, delivered: 0 };
const STATUS = [{ key: "all", label: "All statuses" }, { key: "pending", label: "Submitted" }, { key: "packaging", label: "Packaging" }, { key: "delivering", label: "Delivering" }, { key: "delivered", label: "Delivered" }];
const badge: Record<string, string> = { pending: "border-amber-200 bg-amber-50 text-amber-700", packaging: "border-indigo-200 bg-indigo-50 text-indigo-700", delivering: "border-blue-200 bg-blue-50 text-blue-700", delivered: "border-green-200 bg-green-50 text-green-700" };
const money = (value: number) => `GHS ${Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const date = (value: string) => value ? new Date(value).toLocaleString() : "Not recorded";

export function DeliveriesPage() {
  const { t } = useTheme();
  const [deliveries, setDeliveries] = useState<Delivery[]>([]);
  const [counts, setCounts] = useState<Counts>(EMPTY_COUNTS);
  const [branches, setBranches] = useState<string[]>([]);
  const [pagination, setPagination] = useState({ page: 1, total: 0, totalPages: 1 });
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState("");
  useEffect(() => { const apply = (event?: Event) => { let payload: any = event ? (event as CustomEvent).detail : null; if (!payload) { try { payload = JSON.parse(window.sessionStorage.getItem("customer-support-global-search") || "null"); } catch { payload = null; } } if (payload?.page === "deliveries") { setSearch(payload.query || ""); setPage(1); window.sessionStorage.removeItem("customer-support-global-search"); } }; apply(); window.addEventListener("customer-support-global-search", apply); return () => window.removeEventListener("customer-support-global-search", apply); }, []);
  const [status, setStatus] = useState("all");
  const [branch, setBranch] = useState("all");
  const [selected, setSelected] = useState<Delivery | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const load = async () => {
    setLoading(true); setError("");
    try {
      const params = new URLSearchParams({ page: String(page), per_page: "20", search, status, branch });
      const response = await fetch(`/api/customer-support/deliveries?${params}`, { credentials: "same-origin" });
      const data = await response.json();
      if (!response.ok || !data.ok) throw new Error(data.message || "Unable to load submitted cards.");
      setDeliveries(data.deliveries || []); setCounts(data.counts || EMPTY_COUNTS); setBranches(data.branches || []); setPagination(data.pagination || { page: 1, total: 0, totalPages: 1 });
      setSelected(current => current ? (data.deliveries || []).find((item: Delivery) => item.id === current.id) || null : null);
    } catch (e) { setError(e instanceof Error ? e.message : "Unable to load submitted cards."); }
    finally { setLoading(false); }
  };
  useEffect(() => { const timer = window.setTimeout(() => void load(), 250); return () => window.clearTimeout(timer); }, [page, search, status, branch]);

  const summaries = [
    ["Submitted Cards", counts.total, Package, "text-gray-700", "all"], ["Submitted", counts.pending, Clock3, "text-amber-700", "pending"],
    ["Packaging", counts.packaging, Package, "text-indigo-700", "packaging"], ["Delivering", counts.delivering, Truck, "text-blue-700", "delivering"],
    ["Delivered", counts.delivered, CheckCircle2, "text-green-700", "delivered"],
  ] as const;

  return <div className="h-full overflow-y-auto p-6" style={{ background: t.pageBg }}><div className="mx-auto max-w-[1500px] space-y-5">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-extrabold text-gray-900">Submitted Cards</h1><p className="mt-1 text-sm text-gray-500">Customer delivery status from Inventory</p></div><div className="flex gap-2"><button title="Refresh" onClick={() => void load()} className="rounded-lg border bg-white p-2.5 text-gray-600"><RefreshCw size={16} /></button><a href="/api/customer-support/deliveries/export" className="flex items-center gap-2 rounded-lg border bg-white px-4 py-2 text-sm font-semibold text-gray-700"><Download size={15} />Export</a></div></header>
    {error && <div className="flex justify-between rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700"><span>{error}</span><button onClick={() => setError("")}><X size={15} /></button></div>}
    <div className="grid grid-cols-2 gap-3 md:grid-cols-5">{summaries.map(([label, value, Icon, color, filter]) => <button key={label} onClick={() => { setStatus(filter); setPage(1); }} className={`rounded-lg border bg-white p-4 text-left ${status === filter ? "border-blue-500 ring-1 ring-blue-500" : "border-gray-200"}`}><Icon size={18} className={color} /><strong className="mt-3 block text-2xl text-gray-900">{value}</strong><span className="text-xs font-semibold uppercase text-gray-400">{label}</span></button>)}</div>
    <div className="flex flex-wrap gap-3 rounded-lg border border-gray-200 bg-white p-4"><label className="relative min-w-[280px] flex-1"><Search size={15} className="absolute left-3 top-3 text-gray-400" /><input value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} placeholder="Search customer, phone, product, or agent" className="w-full rounded-lg border border-gray-200 py-2.5 pl-9 pr-3 text-sm" /></label><select value={status} onChange={e => { setStatus(e.target.value); setPage(1); }} className="rounded-lg border border-gray-200 bg-white px-3 py-2.5 text-sm">{STATUS.map(item => <option key={item.key} value={item.key}>{item.label}</option>)}</select><select value={branch} onChange={e => { setBranch(e.target.value); setPage(1); }} className="rounded-lg border border-gray-200 bg-white px-3 py-2.5 text-sm"><option value="all">All branches</option>{branches.map(item => <option key={item}>{item}</option>)}</select></div>
    <div className="overflow-hidden rounded-lg border border-gray-200 bg-white">{loading ? <div className="p-16 text-center text-gray-500">Loading submitted cards...</div> : <><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-400"><tr>{["Product", "Customer", "Branch / Agent", "Payment", "Submitted", "Status", ""].map(title => <th key={title} className="px-4 py-3">{title}</th>)}</tr></thead><tbody>{deliveries.map(item => <tr key={item.id} className="border-t border-gray-100"><td className="px-4 py-3"><div className="flex min-w-[220px] items-center gap-3">{item.productImage ? <img src={item.productImage} alt="" className="h-11 w-11 rounded-md border object-cover" /> : <div className="flex h-11 w-11 items-center justify-center rounded-md bg-gray-100"><Package size={18} className="text-gray-400" /></div>}<div><strong className="block text-gray-800">{item.productName}</strong><span className="text-xs text-gray-500">Qty {item.quantity}{item.purchaseType ? ` · ${item.purchaseType}` : ""}</span></div></div></td><td className="px-4 py-3"><strong className="block text-gray-700">{item.customerName}</strong><span className="text-xs text-gray-500">{item.customerPhone || "No phone"}</span></td><td className="px-4 py-3"><span className="block text-gray-700">{item.branch || "Not assigned"}</span><span className="text-xs text-gray-500">{item.agentName || "No agent"}</span></td><td className="px-4 py-3"><strong className="block text-gray-700">{money(item.amountPaid)}</strong><span className="text-xs text-gray-500">Balance {money(item.amountLeft)}</span></td><td className="px-4 py-3 text-gray-600">{date(item.submittedAt)}<span className="block text-xs text-gray-400">{item.daysWaiting} day(s) waiting</span></td><td className="px-4 py-3"><span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-bold ${badge[item.status]}`}>{item.statusLabel}</span></td><td className="px-4 py-3"><button title="View details" onClick={() => setSelected(item)} className="rounded-md p-2 text-blue-600 hover:bg-blue-50"><Eye size={16} /></button></td></tr>)}{deliveries.length === 0 && <tr><td colSpan={7} className="p-14 text-center text-gray-400">No submitted cards match these filters.</td></tr>}</tbody></table></div><footer className="flex items-center justify-between border-t px-4 py-3 text-sm text-gray-500"><span>{pagination.total} submitted card(s)</span><div className="flex items-center gap-2"><button title="Previous page" disabled={page <= 1} onClick={() => setPage(value => value - 1)} className="rounded border p-2 disabled:opacity-40"><ChevronLeft size={15} /></button><span>Page {pagination.page} of {pagination.totalPages}</span><button title="Next page" disabled={page >= pagination.totalPages} onClick={() => setPage(value => value + 1)} className="rounded border p-2 disabled:opacity-40"><ChevronRight size={15} /></button></div></footer></>}</div>
    {selected && <Detail delivery={selected} onClose={() => setSelected(null)} />}
  </div></div>;
}

function Detail({ delivery, onClose }: { delivery: Delivery; onClose: () => void }) { return <div className="fixed inset-0 z-50 flex justify-end bg-black/35" onClick={onClose}><aside className="h-full w-full max-w-xl overflow-y-auto bg-white shadow-2xl" onClick={e => e.stopPropagation()}><header className="sticky top-0 z-10 flex items-center justify-between border-b bg-white p-5"><div><span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-bold ${badge[delivery.status]}`}>{delivery.statusLabel}</span><h2 className="mt-2 text-lg font-bold text-gray-900">Submitted card details</h2></div><button onClick={onClose} className="rounded-md p-2 text-gray-500"><X size={18} /></button></header><div className="space-y-5 p-5"><section className="flex gap-4 rounded-lg border p-4">{delivery.productImage ? <img src={delivery.productImage} alt={delivery.productName} className="h-24 w-24 rounded-md object-cover" /> : <div className="flex h-24 w-24 items-center justify-center rounded-md bg-gray-100"><Package size={28} className="text-gray-400" /></div>}<div><h3 className="font-bold text-gray-900">{delivery.productName}</h3><p className="mt-1 text-sm text-gray-500">Quantity: {delivery.quantity}</p><p className="text-sm text-gray-500">Purchase type: {delivery.purchaseType || "Not recorded"}</p><p className="mt-2 text-xs text-gray-400">Card ID: {delivery.id}</p></div></section><Section title="Customer"><Line label="Name" value={delivery.customerName} /><Line label="Phone" value={delivery.customerPhone} /><Line label="Branch" value={delivery.branch} /><Line label="Agent" value={delivery.agentName} /></Section><Section title="Payment"><Line label="Product total" value={money(delivery.productTotal)} /><Line label="Amount paid" value={money(delivery.amountPaid)} /><Line label="Amount left" value={money(delivery.amountLeft)} /></Section><Section title="Status history">{delivery.history.length ? <div className="space-y-4">{delivery.history.map((event, index) => <div key={`${event.timestamp}-${index}`} className="border-l-2 border-blue-200 pl-4"><strong className="text-sm text-gray-800">{event.label}</strong><p className="text-xs text-gray-500">{date(event.timestamp)}{event.actorName ? ` · ${event.actorName}` : ""}</p>{event.notes && <p className="mt-1 text-sm text-gray-600">{event.notes}</p>}</div>)}</div> : <p className="text-sm text-gray-400">No status history has been recorded.</p>}</Section></div></aside></div>; }
function Section({ title, children }: { title: string; children: ReactNode }) { return <section className="rounded-lg border p-4"><h3 className="mb-3 font-bold text-gray-900">{title}</h3>{children}</section>; }
function Line({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4 border-b border-gray-100 py-2 text-sm last:border-0"><span className="text-gray-500">{label}</span><strong className="text-right text-gray-700">{value || "Not recorded"}</strong></div>; }
