import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Bell, CheckCheck, CheckSquare, ChevronLeft, ChevronRight, Clock, Package, Phone, RefreshCw, Search, Ticket, X } from "lucide-react";
import { useTheme } from "./ThemeContext";

type Notification = { id: string; type: "ticket" | "task" | "call" | "delivery"; title: string; message: string; priority: string; createdAt: string; reference: string; actionPage: string; read: boolean };
const types = [{ key: "all", label: "All", icon: Bell }, { key: "ticket", label: "Tickets", icon: Ticket }, { key: "task", label: "Tasks", icon: CheckSquare }, { key: "call", label: "Calls", icon: Phone }, { key: "delivery", label: "Deliveries", icon: Package }];
const tones: Record<string, { icon: string; bg: string }> = { ticket: { icon: "text-red-700", bg: "bg-red-50" }, task: { icon: "text-amber-700", bg: "bg-amber-50" }, call: { icon: "text-indigo-700", bg: "bg-indigo-50" }, delivery: { icon: "text-green-700", bg: "bg-green-50" } };
const icons = { ticket: Ticket, task: CheckSquare, call: Phone, delivery: Package };

function relative(value: string) { const time = new Date(value).getTime(); if (!time) return "Unknown time"; const seconds = Math.max(Math.floor((Date.now() - time) / 1000), 0); if (seconds < 60) return "Just now"; if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`; if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`; if (seconds < 604800) return `${Math.floor(seconds / 86400)}d ago`; return new Date(value).toLocaleDateString(); }
function groupLabel(value: string) { const item = new Date(value); const today = new Date(); const yesterday = new Date(); yesterday.setDate(today.getDate() - 1); if (item.toDateString() === today.toDateString()) return "Today"; if (item.toDateString() === yesterday.toDateString()) return "Yesterday"; return item.toLocaleDateString(undefined, { month: "long", year: "numeric" }); }

export function NotificationsPage() {
  const { t } = useTheme();
  const [items, setItems] = useState<Notification[]>([]); const [counts, setCounts] = useState<Record<string, number>>({}); const [unreadCount, setUnreadCount] = useState(0);
  const [type, setType] = useState("all"); const [unreadOnly, setUnreadOnly] = useState(false); const [search, setSearch] = useState(""); const [page, setPage] = useState(1);
  const [pagination, setPagination] = useState({ page: 1, total: 0, totalPages: 1 }); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [updated, setUpdated] = useState("");
  const load = async (quiet = false) => { if (!quiet) setLoading(true); setError(""); try { const params = new URLSearchParams({ type, page: String(page), per_page: "25" }); if (unreadOnly) params.set("unread", "true"); const response = await fetch(`/api/customer-support/notifications?${params}`, { credentials: "same-origin" }); const data = await response.json(); if (!response.ok || !data.ok) throw new Error(data.message || "Unable to load notifications."); setItems(data.notifications || []); setCounts(data.counts || {}); setUnreadCount(data.unreadCount || 0); setPagination(data.pagination || { page: 1, total: 0, totalPages: 1 }); setUpdated(new Date().toLocaleTimeString()); window.dispatchEvent(new CustomEvent("customer-support-notification-count", { detail: data.unreadCount || 0 })); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load notifications."); } finally { setLoading(false); } };
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(true), 30000); return () => window.clearInterval(timer); }, [type, unreadOnly, page]);
  const mark = async (id?: string) => { const response = await fetch("/api/customer-support/notifications", { method: "PATCH", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify(id ? { id } : { all: true }) }); if (response.ok) await load(true); else setError("Unable to update notification state."); };
  const visible = useMemo(() => { const q = search.trim().toLowerCase(); return q ? items.filter(item => [item.title, item.message, item.reference].some(value => value.toLowerCase().includes(q))) : items; }, [items, search]);
  const grouped = visible.reduce<Record<string, Notification[]>>((result, item) => { (result[groupLabel(item.createdAt)] ||= []).push(item); return result; }, {});

  return <div className="min-h-full overflow-y-auto p-6" style={{ background: t.pageBg }}><div className="mx-auto max-w-[1200px] space-y-5">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-extrabold text-gray-900">Notification Center</h1><p className="mt-1 text-sm text-gray-500">{unreadCount ? `${unreadCount} unread operational notification${unreadCount === 1 ? "" : "s"}` : "All notifications are read"}{updated ? ` · Updated ${updated}` : ""}</p></div><div className="flex gap-2"><button title="Refresh notifications" onClick={() => void load()} className="rounded-lg border bg-white p-2.5 text-gray-600"><RefreshCw size={16} /></button>{unreadCount > 0 && <button onClick={() => void mark()} className="flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-bold text-white"><CheckCheck size={16} />Mark all read</button>}</div></header>
    {error && <div className="flex justify-between rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700"><span>{error}</span><button onClick={() => setError("")}><X size={15} /></button></div>}
    <div className="grid grid-cols-2 gap-3 md:grid-cols-5">{types.map(entry => { const Icon = entry.icon; const value = entry.key === "all" ? Object.values(counts).reduce((sum, count) => sum + count, 0) : counts[entry.key] || 0; return <button key={entry.key} onClick={() => { setType(entry.key); setPage(1); }} className={`rounded-lg border bg-white p-4 text-left ${type === entry.key ? "border-blue-500 ring-1 ring-blue-500" : "border-gray-200"}`}><Icon size={17} className="text-blue-600" /><strong className="mt-3 block text-xl text-gray-900">{value}</strong><span className="text-xs font-semibold uppercase text-gray-400">{entry.label}</span></button>; })}</div>
    <div className="flex flex-wrap gap-3 rounded-lg border border-gray-200 bg-white p-4"><label className="relative min-w-[280px] flex-1"><Search size={15} className="absolute left-3 top-3 text-gray-400" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search visible notifications" className="w-full rounded-lg border border-gray-200 py-2.5 pl-9 pr-3 text-sm" /></label><label className="flex cursor-pointer items-center gap-2 rounded-lg border border-gray-200 px-3 py-2 text-sm font-semibold text-gray-600"><input type="checkbox" checked={unreadOnly} onChange={e => { setUnreadOnly(e.target.checked); setPage(1); }} className="h-4 w-4 accent-blue-600" />Unread only</label></div>
    {loading ? <div className="rounded-lg border bg-white p-16 text-center text-gray-500">Loading notifications...</div> : <div className="space-y-6">{Object.entries(grouped).map(([label, rows]) => <section key={label}><h2 className="mb-2 text-xs font-bold uppercase text-gray-400">{label}</h2><div className="overflow-hidden rounded-lg border border-gray-200 bg-white">{rows.map(item => <NotificationRow key={item.id} item={item} onRead={() => void mark(item.id)} />)}</div></section>)}{visible.length === 0 && <div className="rounded-lg border bg-white p-16 text-center"><Bell size={32} className="mx-auto mb-3 text-gray-300" /><p className="text-sm text-gray-500">No notifications match this view.</p></div>}</div>}
    <footer className="flex items-center justify-between rounded-lg border bg-white px-4 py-3 text-sm text-gray-500"><span>{pagination.total} notification(s)</span><div className="flex items-center gap-2"><button title="Previous page" disabled={page <= 1} onClick={() => setPage(value => value - 1)} className="rounded border p-2 disabled:opacity-40"><ChevronLeft size={15} /></button><span>Page {pagination.page} of {pagination.totalPages}</span><button title="Next page" disabled={page >= pagination.totalPages} onClick={() => setPage(value => value + 1)} className="rounded border p-2 disabled:opacity-40"><ChevronRight size={15} /></button></div></footer>
  </div></div>;
}

function NotificationRow({ item, onRead }: { item: Notification; onRead: () => void }) { const Icon = icons[item.type] || Bell; const tone = tones[item.type] || { icon: "text-gray-600", bg: "bg-gray-50" }; return <article className={`flex items-start gap-4 border-b border-gray-100 p-4 last:border-0 ${item.read ? "bg-white" : "bg-blue-50/50"}`}><button onClick={onRead} title={item.read ? "Notification read" : "Mark as read"} className={`flex h-10 w-10 flex-none items-center justify-center rounded-md ${tone.bg}`}><Icon size={18} className={tone.icon} /></button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className={`text-sm text-gray-900 ${item.read ? "font-semibold" : "font-extrabold"}`}>{item.title}</h3>{item.priority !== "Normal" && <span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${item.priority === "Critical" ? "bg-red-100 text-red-700" : "bg-amber-100 text-amber-700"}`}>{item.priority}</span>}{!item.read && <span className="h-2 w-2 rounded-full bg-blue-600" />}</div><p className="mt-1 text-sm text-gray-600">{item.message}</p><div className="mt-2 flex items-center gap-3 text-xs text-gray-400"><span className="flex items-center gap-1"><Clock size={11} />{relative(item.createdAt)}</span><span>{new Date(item.createdAt).toLocaleString()}</span></div></div><button onClick={() => { if (!item.read) onRead(); window.location.hash = item.actionPage; }} className="flex-none rounded-md border border-gray-200 px-3 py-1.5 text-xs font-bold text-blue-600">View</button></article>; }
