import { useEffect, useState, type ReactNode } from "react";
import { AlertTriangle, CheckCircle2, Clock, Headphones, RefreshCw, Ticket, Truck, X } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useTheme } from "./ThemeContext";

type Metrics = { totalTickets: number; openTickets: number; resolvedTickets: number; resolutionRate: number; slaCompliance: number; avgResolutionHours: number; totalCalls: number; callResolutionRate: number; deliveryCompletionRate: number };
type Performance = { branch?: string; agent?: string; tickets: number; resolved: number; open: number; breached: number; critical: number; resolutionRate: number; slaRate: number; avgResolutionHours: number; score: number };
type Month = { month: string; tickets: number; resolved: number; open: number; slaRate: number };
type Slice = { name: string; value: number };
type Alert = { level: string; title: string; detail: string };
const EMPTY: Metrics = { totalTickets: 0, openTickets: 0, resolvedTickets: 0, resolutionRate: 0, slaCompliance: 0, avgResolutionHours: 0, totalCalls: 0, callResolutionRate: 0, deliveryCompletionRate: 0 };

export function ReportsPage() {
  const { t } = useTheme();
  const [data, setData] = useState<{ metrics: Metrics; monthly: Month[]; topBranches: Performance[]; topAgents: Performance[]; poorBranches: Performance[]; poorAgents: Performance[]; issues: Slice[]; statuses: Slice[]; alerts: Alert[] }>({ metrics: EMPTY, monthly: [], topBranches: [], topAgents: [], poorBranches: [], poorAgents: [], issues: [], statuses: [], alerts: [] });
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [updated, setUpdated] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const response = await fetch("/api/customer-support/reports", { credentials: "same-origin" }); const result = await response.json(); if (!response.ok || !result.ok) throw new Error(result.message || "Unable to load reports."); setData({ metrics: result.metrics || EMPTY, monthly: result.monthly || [], topBranches: result.topBranches || [], topAgents: result.topAgents || [], poorBranches: result.poorBranches || [], poorAgents: result.poorAgents || [], issues: result.issues || [], statuses: result.statuses || [], alerts: result.alerts || [] }); setUpdated(new Date().toLocaleTimeString()); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load reports."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const m = data.metrics;
  const cards = [
    ["Total Tickets", m.totalTickets, `${m.openTickets} currently open`, Ticket, "bg-blue-50 text-blue-700"],
    ["Resolution Rate", `${m.resolutionRate}%`, `${m.resolvedTickets} resolved`, CheckCircle2, "bg-green-50 text-green-700"],
    ["SLA Compliance", `${m.slaCompliance}%`, "within committed time", Clock, "bg-indigo-50 text-indigo-700"],
    ["Avg Resolution", `${m.avgResolutionHours}h`, "resolved ticket average", RefreshCw, "bg-amber-50 text-amber-700"],
    ["Call Resolution", `${m.callResolutionRate}%`, `${m.totalCalls} logged calls`, Headphones, "bg-purple-50 text-purple-700"],
    ["Delivery Completion", `${m.deliveryCompletionRate}%`, "submitted cards delivered", Truck, "bg-emerald-50 text-emerald-700"],
  ] as const;
  return <div className="min-h-full overflow-y-auto p-6" style={{ background: t.pageBg }}><div className="mx-auto max-w-[1550px] space-y-5">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-extrabold text-gray-900">Support Performance Reports</h1><p className="mt-1 text-sm text-gray-500">Live ticket, call, SLA, and delivery performance{updated ? ` · Updated ${updated}` : ""}</p></div><button onClick={() => void load()} className="flex items-center gap-2 rounded-lg border bg-white px-4 py-2 text-sm font-semibold text-gray-700"><RefreshCw size={15} />Refresh</button></header>
    {error && <div className="flex justify-between rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700"><span>{error}</span><button onClick={() => setError("")}><X size={15} /></button></div>}
    {loading ? <div className="rounded-lg border bg-white p-16 text-center text-gray-500">Loading reports...</div> : <>
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-3 xl:grid-cols-6">{cards.map(([label, value, sub, Icon, tone]) => <article key={label} className="rounded-lg border border-gray-200 bg-white p-4"><div className={`flex h-9 w-9 items-center justify-center rounded-md ${tone}`}><Icon size={18} /></div><strong className="mt-4 block text-2xl text-gray-900">{value}</strong><h2 className="mt-1 text-xs font-bold uppercase text-gray-500">{label}</h2><p className="mt-1 text-xs text-gray-400">{sub}</p></article>)}</div>
      {data.alerts.length > 0 && <Panel title="Operational Attention" subtitle="Automatically generated from open workload and SLA performance"><div className="grid gap-3 lg:grid-cols-2">{data.alerts.map(alert => <div key={alert.title} className={`flex gap-3 rounded-lg border p-4 ${alert.level === "critical" ? "border-red-200 bg-red-50" : "border-amber-200 bg-amber-50"}`}><AlertTriangle size={18} className={alert.level === "critical" ? "text-red-700" : "text-amber-700"} /><div><strong className="text-sm text-gray-900">{alert.title}</strong><p className="mt-1 text-sm text-gray-600">{alert.detail}</p></div></div>)}</div></Panel>}
      <div className="grid gap-5 xl:grid-cols-2"><Panel title="Six-Month Ticket Trend" subtitle="Created, resolved, and remaining open by month"><Chart height={300}><BarChart data={data.monthly}><CartesianGrid strokeDasharray="3 3" stroke="#E5E7EB" /><XAxis dataKey="month" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} /><Tooltip /><Legend /><Bar dataKey="tickets" name="Created" fill="#93C5FD" radius={[3,3,0,0]} /><Bar dataKey="resolved" name="Resolved" fill="#4ADE80" radius={[3,3,0,0]} /><Bar dataKey="open" name="Open" fill="#FBBF24" radius={[3,3,0,0]} /></BarChart></Chart></Panel><Panel title="SLA Trend" subtitle="Monthly compliance percentage"><Chart height={300}><LineChart data={data.monthly}><CartesianGrid strokeDasharray="3 3" stroke="#E5E7EB" /><XAxis dataKey="month" tick={{ fontSize: 11 }} /><YAxis domain={[0,100]} tick={{ fontSize: 11 }} /><Tooltip /><Line type="monotone" dataKey="slaRate" name="SLA compliance" stroke="#2563EB" strokeWidth={3} /></LineChart></Chart></Panel></div>
      <div className="grid gap-5 xl:grid-cols-2"><PerformancePanel title="Top Performing Branches" subtitle="Highest combined resolution and SLA performance" rows={data.topBranches} nameKey="branch" positive /><PerformancePanel title="Branches Requiring Attention" subtitle="Prioritized by SLA breaches, open backlog, and poor results" rows={data.poorBranches} nameKey="branch" /></div>
      <div className="grid gap-5 xl:grid-cols-2"><PerformancePanel title="Top Performing Agents" subtitle="Strong resolution output and SLA performance" rows={data.topAgents} nameKey="agent" positive /><PerformancePanel title="Agents Requiring Attention" subtitle="Agents with more open tickets, breaches, or poor results" rows={data.poorAgents} nameKey="agent" /></div>
      <div className="grid gap-5 xl:grid-cols-2"><Breakdown title="Complaint and Ticket Categories" subtitle="Volume by issue type" rows={data.issues} color="#2563EB" /><Breakdown title="Ticket Status Distribution" subtitle="Current workflow distribution" rows={data.statuses} color="#16A34A" /></div>
    </>}
  </div></div>;
}

function PerformancePanel({ title, subtitle, rows, nameKey, positive }: { title: string; subtitle: string; rows: Performance[]; nameKey: "branch" | "agent"; positive?: boolean }) { return <Panel title={title} subtitle={subtitle}><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-400"><tr>{[nameKey === "branch" ? "Branch" : "Agent", "Tickets", "Resolved", "Open", "Breaches", "Resolution", "SLA", "Score"].map(h => <th key={h} className="px-3 py-2.5">{h}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={row[nameKey]} className="border-t"><td className="px-3 py-3 font-bold text-gray-800"><span className={`mr-2 inline-flex h-5 w-5 items-center justify-center rounded-full text-[10px] ${positive ? "bg-green-50 text-green-700" : "bg-red-50 text-red-700"}`}>{index + 1}</span>{row[nameKey]}</td><Cell>{row.tickets}</Cell><Cell>{row.resolved}</Cell><Cell danger={!positive && row.open > 0}>{row.open}</Cell><Cell danger={row.breached > 0}>{row.breached}</Cell><Cell><Rate value={row.resolutionRate} /></Cell><Cell><Rate value={row.slaRate} /></Cell><Cell><strong className={row.score >= 85 ? "text-green-700" : row.score >= 70 ? "text-amber-700" : "text-red-700"}>{row.score}</strong></Cell></tr>)}{!rows.length && <tr><td colSpan={8} className="p-10 text-center text-gray-400">No performance records available.</td></tr>}</tbody></table></div></Panel>; }
function Breakdown({ title, subtitle, rows, color }: { title: string; subtitle: string; rows: Slice[]; color: string }) { const max = rows[0]?.value || 1; return <Panel title={title} subtitle={subtitle}><div className="space-y-4">{rows.map((row, index) => <div key={row.name}><div className="mb-1 flex justify-between text-sm"><span className="font-medium text-gray-700">{row.name}</span><strong>{row.value}</strong></div><div className="h-2 rounded-full bg-gray-100"><div className="h-full rounded-full" style={{ background: color, width: `${row.value * 100 / max}%`, opacity: Math.max(.4, 1 - index * .07) }} /></div></div>)}{!rows.length && <p className="py-8 text-center text-gray-400">No records available.</p>}</div></Panel>; }
function Panel({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) { return <section className="rounded-lg border border-gray-200 bg-white p-5"><h2 className="font-bold text-gray-900">{title}</h2><p className="mb-5 mt-1 text-xs text-gray-400">{subtitle}</p>{children}</section>; }
function Chart({ height, children }: { height: number; children: ReactNode }) { return <div style={{ height }}><ResponsiveContainer width="100%" height="100%">{children as never}</ResponsiveContainer></div>; }
function Cell({ children, danger }: { children: ReactNode; danger?: boolean }) { return <td className={`px-3 py-3 ${danger ? "font-bold text-red-600" : "text-gray-600"}`}>{children}</td>; }
function Rate({ value }: { value: number }) { return <span className={`rounded-full px-2 py-1 text-xs font-bold ${value >= 85 ? "bg-green-50 text-green-700" : value >= 70 ? "bg-amber-50 text-amber-700" : "bg-red-50 text-red-700"}`}>{value}%</span>; }
